GestionUtilisateur/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('manage_user/', include('manage_user.urls', namespace='manage_user')),
]

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login, name='login')
]

manage_user/urls.py
from django.urls import path
from . import views

app_name = 'manage_user'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('logout/', views.logout_user, name='logout_user'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_migrate
from django.dispatch import receiver



class DataBase(models.Model):
    CHOICES = (
        ('Scopus', 'Scopus'),
        ('PubMed', 'PubMed'),
        ('Dimensions', 'Dimensions'),
        ('Web of Science', 'Web of Science'),
    )
    name = models.CharField(max_length=14, choices=CHOICES, unique=True)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    databases = models.ManyToManyField(DataBase)

    def __str__(self):
        return self.user.username
    
@receiver(post_migrate)
def create_databases(sender, **kwargs):
    for choice, _ in DataBase.CHOICES:
        DataBase.objects.get_or_create(name=choice)

manage_user/models.py
from django.db import models

# Create your models here.

manage_user/forms.py
from django import forms
from django.contrib.auth.models import User
from login.models import UserProfile, DataBase
from django.core.exceptions import ValidationError

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')
    databases = forms.ModelMultipleChoiceField(queryset=DataBase.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password','confirm_password','email', 'databases']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('confirm_password')

        if password and password2 and password != password2:
            raise ValidationError("Passwords don't match")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            userProfile = UserProfile(user=user)
            userProfile.save()
            userProfile.databases.set(self.cleaned_data['databases'])
        return user

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.views import LoginView

def login(request):
    return LoginView.as_view(template_name='login.html')(request)

manage_user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import RegistrationForm
from login.models import UserProfile
from django.contrib.auth.models import User


def home(request):
    users = User.objects.all()
    return render(request, 'home.html', {'users': users})

def edit_user(request, user_id):
    user = UserProfile.objects.get(user_id=user_id)
    if request.method == 'POST':
        form = RegistrationForm(request.POST, instance=user.user)
        if form.is_valid():
            user = form.save()
            return redirect('manage_user:home')
    else:
        form = RegistrationForm(instance=user.user, initial={'databases':user.databases.all()})
    return render(request, 'add_user.html', {'form': form, 'user': user, 'button_text': 'Edit', 'form_title': 'Edit User'})

def delete_user(request, user_id):
    users = UserProfile.objects.get(user_id=user_id)
    users.user.delete()
    return redirect('manage_user:home')

def logout_user(request):
    logout(request)
    return redirect('login')

def add_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('manage_user:home')
    else:
        form = RegistrationForm()
    return render(request, 'add_user.html', {'form': form, 'button_text': 'Add', 'form_title': 'Add User'})

login/templates/login.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">

    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input id="username" type="text" name="username">
        <label for="password">Password:</label>
        <input id="password" type="password" name="password">
        <button type="submit">Login</button>
    </form>
{% endblock %}

manage_user/templates/add_user.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ form_title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{{ button_text }}</button>
  </form>
  <a href="{% url 'manage_user:home' %}">Retour</a>
{% endblock %}

manage_user/templates/home.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
    <h2>User List</h2>
    <div class="actions">
        <a href="{% url 'manage_user:add_user' %}">Add User</a>
        <a href="{% url 'manage_user:logout_user' %}">Logout</a>
    </div>
    <div class="table-container">
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Databases</th>
            <th>Actions</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>
                {% for database in user.userprofile.databases.all %}
                    {{ database.name }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'manage_user:edit_user' user.id %}">Edit</a> |
                <a href="{% url 'manage_user:delete_user' user.id %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Gestion Utilisateur</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="main-content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>